### ISSUE TITLE
Can I contribute?

### ISSUE THREAD

**Issue by aarona** [ruby-odata/odata#16]
Hi All,

Just following the instructions on the README to post an issue if I'd like to contribute. I have a client that wants to interface with a CRM that uses OData and I need to mutate (insert basically) and from the current documentation (and a quick look at the code) it looks like querying is only possible at the moment. I've only started looking at OData yesterday so I will be approaching this from a newbie perspective. Looks like there hasn't been any changes to the project in a while. Are you still maintaining this project?

**Comment by plainprogrammer** [comment]
I have not been active in maintaining this project for a few years. But I will gladly accept pull requests and tag new releases.
